/*Copier à partir d’ici*/
-- Création du USER SQL
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER "IPIDATABASE" IDENTIFIED BY "MDPIPIDATABASE";
ALTER USER "IPIDATABASE"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;
-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "IPIDATABASE" ;
GRANT CREATE ANY INDEX TO "IPIDATABASE" ;
GRANT CREATE VIEW TO "IPIDATABASE" ;
GRANT CREATE SESSION TO "IPIDATABASE";
GRANT SELECT ANY TABLE TO "IPIDATABASE" ;
GRANT DELETE ANY TABLE TO "IPIDATABASE" ;
GRANT CREATE TABLE TO "IPIDATABASE" ;
GRANT DROP ANY TABLE TO "IPIDATABASE" ;
GRANT UNDER ANY TYPE TO "IPIDATABASE" ;
GRANT CREATE TYPE TO "IPIDATABASE" ;
GRANT DROP ANY TYPE TO "IPIDATABASE" ;
GRANT EXECUTE ANY PROCEDURE TO "IPIDATABASE" ;
GRANT EXECUTE ANY PROGRAM TO "IPIDATABASE" ;
GRANT EXECUTE ANY TYPE TO "IPIDATABASE" ;
GRANT DROP ANY INDEX TO "IPIDATABASE" ;
GRANT UPDATE ANY TABLE TO "IPIDATABASE" ;
GRANT DROP ANY VIEW TO "IPIDATABASE" ;
GRANT UNDER ANY VIEW TO "IPIDATABASE" ;
GRANT GRANT ANY PRIVILEGE TO "IPIDATABASE" ;
GRANT CREATE ANY VIEW TO "IPIDATABASE" ;
GRANT FORCE TRANSACTION TO "IPIDATABASE" ;
GRANT DROP ANY PROCEDURE TO "IPIDATABASE" ;
GRANT UNLIMITED TABLESPACE TO "IPIDATABASE" ;
GRANT CREATE ANY TRIGGER TO "IPIDATABASE" ;
GRANT CREATE ANY TABLE TO "IPIDATABASE" ;
GRANT CREATE ANY TYPE TO "IPIDATABASE" ;
GRANT CREATE PROCEDURE TO "IPIDATABASE" ;
GRANT GRANT ANY ROLE TO "IPIDATABASE" ;
/*Fin de la copie*/
GRANT CREATE SEQUENCE TO "IPIDATABASE";
